name: Feature Request
description: Suggest a new feature or enhancement for KLAUSS
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Thanks for suggesting a new feature!

  - type: textarea
    id: problem
    attributes:
      label: Current Problem
      description: What problem does this feature solve?
      placeholder: "Currently, KLAUSS cannot..."
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: "I would like KLAUSS to..."
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would you use this feature?
      placeholder: "This would allow me to..."
    validations:
      required: false

  - type: textarea
    id: api-example
    attributes:
      label: Proposed API/Usage
      description: What would the API or usage look like? (optional)
      placeholder: |
        ```python
        orch.new_feature(...)
        ```
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or workarounds have you considered?
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information, examples, or references
    validations:
      required: false
