name: Implementation Work
description: Internal implementation task or work item
title: "[IMPL] "
labels: ["implementation"]
body:
  - type: markdown
    attributes:
      value: |
        ## Implementation Work Item
        Use this template for internal implementation tasks that address customer reports or feature development.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Brief description of what we're building or fixing
      placeholder: "This implementation will..."
    validations:
      required: true

  - type: textarea
    id: related-issues
    attributes:
      label: Related Customer Reports
      description: Link to customer issues this addresses
      placeholder: |
        - Closes #XX - [brief description]
        - Relates to #YY - [brief description]
    validations:
      required: false

  - type: textarea
    id: implementation
    attributes:
      label: Proposed Implementation
      description: High-level approach or plan
      placeholder: |
        1. First step...
        2. Second step...
    validations:
      required: false

  - type: textarea
    id: success-criteria
    attributes:
      label: Success Criteria
      description: How we know this work is complete
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information
    validations:
      required: false
